### ISSUE TITLE
Sorry! I have a question unrelated to this Project

### ISSUE THREAD

**Issue by SlimeVRX** [lithiumice/YOLOX#1]
Hi @lithiumice

Sorry I have no way of contacting you

I found your video channel on [Youtube](https://www.youtube.com/@user-dg5tu6eg3w/videos). I am very impressed with your work
Tracking accuracy and smoothness are superior to PyMAF-X. It would be great if applied in Mocap and Vtuber

Do you plan to publish your article in the near future? Do you have other information? I'm looking forward

Thank you for your great work!

Best wishes,

Tin Nguyen Thanh

**Comment by SlimeVRX** [comment]
I found Speech2gesture [dataset](https://people.eecs.berkeley.edu/~shiry/projects/speech2gesture/). Did you train through this dataset?

**Comment by SlimeVRX** [comment]
My job is working in an Artist team. I am developing a high-precision Mocap system.

Can you give me your SMPL-X model results so I can do a demo with Metahuman in Unreal Engine

This is my demo
- Link1: https://youtu.be/X8nYpREPvRI
- Link2: https://youtu.be/U5kN4Fcjxos

Thank you very much!

**Comment by lithiumice** [comment]
Thank you for your interest in this job. The demo video you mentioned is a part of the corresponding article, which can be found at https://talkshow.is.tue.mpg.de/. The corresponding code link is https://github.com/yhw-yhw/SHOW. We will work to improve the code project with more details as soon as possible.

**Comment by lithiumice** [comment]
> Hi @lithiumice
> 
> Sorry I have no way of contacting you
> 
> I found your video channel on [Youtube](https://www.youtube.com/@user-dg5tu6eg3w/videos). I am very impressed with your work Tracking accuracy and smoothness are superior to PyMAF-X. It would be great if applied in Mocap and Vtuber
> 
> Do you plan to publish your article in the near future? Do you have other information? I'm looking forward
> 
> Thank you for your great work!
> 
> Best wishes,
> 
> Tin Nguyen Thanh

Thank you for your interest in this job. The demo video you mentioned is a part of the corresponding article, which can be found at https://talkshow.is.tue.mpg.de/. The corresponding code link is https://github.com/yhw-yhw/SHOW. We will work to improve the code project with more details as soon as possible.

**Comment by SlimeVRX** [comment]
Thanks for notifying me! Thank you for the team's work!
